FROM postgres
MAINTAINER Edilva <edilva.intin@gmail.com>
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB atividade-avaliativa-contatos
COPY create.sql /docker-entrypoint-initdb.d/
